import "@/styles/globals.scss";
import * as pages from "@/components";
import { CartProvider } from "@/components/store";

export const metadata = {
    title: "DropShipping",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
                <CartProvider>
                    <pages.Header />
                    {children}
                    <pages.Footer />
                </CartProvider>
            </body>
        </html>
    );
}
